[package]
name = "hoomd-workflow"
edition = "2024"

[dependencies]
hoomd-geometry = { path = "../hoomd-rs/hoomd-geometry", version = "0.0.0"}
hoomd-gsd = { path = "../hoomd-rs/hoomd-gsd", version = "0.0.0"}
hoomd-interaction = { path = "../hoomd-rs/hoomd-interaction", version = "0.0.0"}
hoomd-mc = { path = "../hoomd-rs/hoomd-mc", version = "0.0.0"}
hoomd-microstate = { path = "../hoomd-rs/hoomd-microstate", version = "0.0.0"}
hoomd-simulation = { path = "../hoomd-rs/hoomd-simulation", version = "0.0.0"}
hoomd-spatial = { path = "../hoomd-rs/hoomd-spatial", version = "0.0.0"}
hoomd-utility = { path = "../hoomd-rs/hoomd-utility", version = "0.0.0"}
hoomd-vector = { path = "../hoomd-rs/hoomd-vector", version = "0.0.0"}

anyhow = "1.0.100"
clap = {version = "4.5.48", features = ["derive"]}
env_logger = "0.11.8"
log = "0.4.28"
postcard = {version = "1.1.3", default-features = false, features = ["use-std"]}
parquet = { version = "58.0.0", default-features=false }
parquet_derive = { version = "58.0.0", default-features=false }
serde = { version = "1.0.228", features = ["derive"]}
